parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        types:
            basket_id: App\Project\Infrastructure\Basket\Types\BasketIdType
            item_id: App\Project\Infrastructure\Basket\Types\ItemIdType
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Authorization: #FosOauthBundle
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Authorization/Entity/Oauth2'
                prefix: 'App\Authorization\Entity\Oauth2'
                alias: App
            Project:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Project/Infrastructure/doctrine/mapping'
                prefix: 'App\Project\Domain'
                alias: App
