App\Project\Domain\User\Entity\User:
    type: entity
    table: users
    repositoryClass: App\Project\Infrastructure\User\UserRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 100
        email:
            type: string
        password:
            type: string